SELECT * FROM tab;
SELECT * FROM employees;
SELECT FIRST_NAME, JOB_ID, MANAGER_ID, DEPARTMENT_ID FROM employees;
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, MANAGER_ID FROM DEPARTMENTS;
SELECT * FROM DEPARTMENTS;

